site_name: lib-cmapper
site_url: https://codemapper.com/
nav:
    - Home: index.md
    - About: about.md
    - lib-cmapper:
        - Data_Structures: 
            - Data_Structure:
                - Graph : ./Data_Structures/Data_Structure/graph/graph.md
                - List : ./Data_Structures/Data_Structure/list/list.md
                - Node : ./Data_Structures/Data_Structure/node/node.md
                - Queue : ./Data_Structures/Data_Structure/queue/queue.md
                - Tree : ./Data_Structures/Data_Structure/tree/tree.md

            - Data_Field : ./Data_Structures/datafield.md

        - Files:
            - File List:
                - Graph :
                    - graph.c : ./Files/File_List/graph/graph_8c.md
                    - graph.h : ./Files/File_List/graph/graph_8h.md

                - Linked List :
                    - linked_list.c : ./Files/File_List/linked_list/linked_list_8c.md
                    - linked_list.h : ./Files/File_List/linked_list/linked_list_8h.md

                - Queue :
                    - queue.c : ./Files/File_List/queue/queue_8c.md
                    - queue.h : ./Files/File_List/queue/queue_8h.md

                - Tables : 
                    - table.c : ./Files/File_List/table/table_8c.md  
                    - table.h : ./Files/File_List/table/table_8h.md

                - Tree : 
                    - tree.c : ./Files/File_List/tree/tree_8c.md
                    - tree.h : ./Files/File_List/tree/tree_8h.md

theme: readthedocs