site_name: lib-cmapper
site_url: https://codemapper.com/
nav:
    - Home: index.md
    - About: about.md
    - Structure de données:
        - Node : ./Data_Structures/node/node.md
        - Tableaux : ./Data_Structures/table/table_8c.md
        - Graphes : ./Data_Structures/graph/graph_8c.md
        - Listes chainées : ./Data_Structures/list/linked_list_8c.md
        - Files : ./Data_Structures/queue/queue_8c.md
        - Arbres : ./Data_Structures/tree/tree_8c.md
                
theme: readthedocs
