site_name: lib-cmapper
site_url: https://codemapper.com/
nav:
    - Home: index.md
    - About: about.md
    - lib-cmapper:
        - Data_Structures: 
            - Node : ./Data_Structures/node/node.md
            - Tables : 
                - table.c : ./Data_Structures/table/table_8c.md
            - Graph :
                - Graph : ./Data_Structures/graph/graph.md
                - graph.c : ./Data_Structures/graph/graph_8c.md
            - Linked List :
                - List : ./Data_Structures/list/list.md
                - linked_list.c : ./Data_Structures/list/linked_list_8c.md
            - Queue :
                - Queue : ./Data_Structures/queue/queue.md
                - queue.c : ./Data_Structures/queue/queue_8c.md
            - Tree : 
                - Tree : ./Data_Structures/tree/tree.md
                - tree.c : ./Data_Structures/tree/tree_8c.md
                
            
theme: flatly
